const quizData = [
    {
        question: "What does HTML stand for?",
        a: "Hypertext Markup Language",
        b: "Cascading Style Sheet",
        c: "Jason Object Notation",
        d: "Helicopters Terminals Motorboats Lamborginis",
        correct: "a",
    },
    {
        question: "What year was HTML first proposed?",
        a: "1990",
        b: "1989",
        c: "1991",
        d: "1995",
        correct: "b",
    },
    {
        question: "Who is known as the father of HTML?",
        a: "Brendan Eich",
        b: "Tim Berners-Lee",
        c: "Håkon Wium Lie",
        d: "Douglas Crockford",
        correct: "b",
    },
    {
        question: "Which HTML tag is used to define an internal style sheet?",
        a: "<script>",
        b: "<css>",
        c: "<style>",
        d: "<link>",
        correct: "c",
    },
    {
        question: "Which is the correct HTML element for the largest heading?",
        a: "<heading>",
        b: "<h6>",
        c: "<h1>",
        d: "<head>",
        correct: "c",
    },
    {
        question: "Which HTML attribute is used to define inline styles?",
        a: "class",
        b: "style",
        c: "styles",
        d: "font",
        correct: "b",
    },
    {
        question: "Which HTML tag is used to define an unordered list?",
        a: "<ul>",
        b: "<ol>",
        c: "<li>",
        d: "<list>",
        correct: "a",
    },
    {
        question: "What is the correct HTML element for inserting a line break?",
        a: "<break>",
        b: "<lb>",
        c: "<br>",
        d: "<newline>",
        correct: "c",
    },
    {
        question: "Which HTML tag is used to define a table?",
        a: "<table>",
        b: "<tab>",
        c: "<tbl>",
        d: "<t>",
        correct: "a",
    },
    {
        question: "What does the <img> tag require?",
        a: "alt",
        b: "src",
        c: "title",
        d: "both alt and src",
        correct: "d",
    }
];
